/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main (void);
GtkWidget* create_error_dialog_quit (void);
GtkWidget* create_about2 (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_dialog4 (void);
GtkWidget* create_dialog5 (void);
